index:
    path: /
    controller: App\Controller\IndexController::index

registration:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

